FROM python:3.11-slim-bookworm

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    curl \
    redis-tools \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copia os arquivos e instala dependências
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Copia a aplicação
COPY . /app

EXPOSE 8000

CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:8000", "wsgi:app"]
